sudo: required
services: docker
language: java
jdk: openjdk8
before_script:
- chmod +x gradlew
script:
- ./gradlew build
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- docker build -t meterng:armhf -f Dockerfile.armhf .
after_success:
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD" 
- docker tag meterng:armhf meterng:latest $DOCKER_USER/meterng:armhf $DOCKER_USER/meterng:latest
- docker push $DOCKER_USER/meterng

env:
  global:
  - secure: OgHGtXgly/2E8aafc1p6wvQo3U6TZr3l+9thQQGqIZUBtiQWm4yzndmJ8+4OnJSPKoMpLBBVAAtHocqzHiIWaSLHQSds2UN1KQSeleyP9lTqX+ZC2FCuXRmAWrmZT4BjoUScWFCyqHuWwgw4lXI8NOhdebi0Pq9rVgkh61Eh/J2WoPs6uCR7oCAkCDxFkbV1yjgtmjAoolwk0vnpMAKhtsUAuZl6ppEcl65mg/ehctr/bBa7MveFiMqHSFyD6lpuK2Xf6kqYHm/wXGvOshYocffsYdVl5VW70FrclHoqgC2OMgtyAIumG51ICbt3d59RrMhKm1MGiT38FJGewJtuokp8z8/WLxDwRFE1IwBb+5hfrYW8gFsQN1STcQNjIvQLnzjifMNwur/SgRZFN7EnCmmfJWUkJ2yu58cRfnUWnMm4fkZWRusqMQmEY+7j4CE4XDYAXvtluOvwwKH8ydpv6cjHQ9p++LFrLOgm22dhn4GtEzH9vlKQwbMLRYySX2aik94PW1+sgzGP2YChRzj5QQbvajZGQ5qmuSjXmXjExeJFBpJjZoeL8xHHUw96+BMgPEOnea4YiCgYkEIrdwX1yYebCCyj7VqIxpU+MESLmfWMD6fimG6vAZuAlTjNY40xQAjZSrP8sLVfHVYrqORimxtnySJ6DEo8pArjiOzXPZ8=
  - secure: KI6XPFtGRUMhrsurPrhsMKRtwVzLmAluzrD6uADsxbVCrx0z2+15LRO2vklvDwkyvflsCm0HPPok/VRQa18ZIcF8bnnEgayR0wQpAH38HVWRpb0EeUWgBcHcUEyfiudRVCPDxtFDmlXDDE+ARvbTGmgPd9qn2HY/fn8IMAOsvjudimxsV1uI4PLseS5YvADZ6x2ejLhtzgjYZ/9+lelTkElL9jcgdwCSGWsXARVgddZsV6jt7VtkiNh47lENkVPZLM0gtj5NwX6K10lydqkuIUsvscVgPHh/SE2aeQ9s6Lxwc4jMAB4eNjLUY7ih2V44WXPYMZE76hCKapjvlgd08i+D0JipYLzVVjmhT58Z8436vTI/Z+0vL4ieM5qcC3J1U4bLVDjsrjdsxbs3d0ka6kFNHSqN4e5GgieSGbytxhAKWtz5NkQCJt65tDUk3BwZG6uaMDOVri3lcoedAKkaKGljsWnBMU2auws0drlYOzrb1F64H7WpIHL5C4P7p01pMGjerYmtCAsWQgtFNQiuSQ5LO8BXrz1uMSpNFX1Fn1efN1MbGtPvGzT1EEzW3w5skxh77J4XM+didkqv4TMh731AfBBxJr3ifLTSHsLjl1GsvZ9VIxnV6N1IvbdYlWtXGC0dffqiP8i4lm8H5sCXxi4Kp8oK7Go2/cR3SFfXxoI=
